version: 2.0

# heavily inspired by https://raw.githubusercontent.com/pinax/pinax-wiki/6bd2a99ab6f702e300d708532a6d1d9aa638b9f8/.circleci/config.yml

common: &common
  working_directory: ~/repo
  steps:
    - checkout
    - run:
        name: install ipfs
        command:
          wget https://dist.ipfs.io/go-ipfs/v0.4.19/go-ipfs_v0.4.19_linux-amd64.tar.gz &&
          tar xvfz go-ipfs_v0.4.19_linux-amd64.tar.gz &&
          sudo cp go-ipfs/ipfs /usr/local/bin && 
          ipfs init
    - run:
        name: start ipfs node in background
        command: ipfs daemon
        background: true
    - run:
        name: install solidity compiler
        command: |
          SOL_BIN_PATH=$(dirname $(which python))/solc
          sudo wget "https://github.com/ethereum/solidity/releases/download/v0.5.9/solc-static-linux" -O ${SOL_BIN_PATH}
          sudo chmod +x ${SOL_BIN_PATH}
          solc --version
    - run:
        name: merge pull request base
        command: ./.circleci/merge_pr.sh
    - run:
        name: merge pull request base (2nd try)
        command: ./.circleci/merge_pr.sh
        when: on_fail
    - run:
        name: merge pull request base (3nd try)
        command: ./.circleci/merge_pr.sh
        when: on_fail
    - restore_cache:
        keys:
          - cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
    - run:
        name: install dependencies
        command: pip install --user tox
    - run:
        name: run tox
        command: ~/.local/bin/tox -r
    - save_cache:
        paths:
          - .hypothesis
          - .tox
          - ~/.cache/pip
          - ~/.local
          - ./eggs
        key: cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}

jobs:
  doctest:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: doctest
  lint:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: lint
  py37-core:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: py37-core
          WEB3_INFURA_PROJECT_ID: 4f1a358967c7474aae6f8f4a7698aefc
          ETHPM_CLI_ETHERSCAN_API_KEY: RYKF6YJS1N2F5PUFA9Q1P9VG92R8N7NE3G

workflows:
  version: 2
  test:
    jobs:
      - doctest
      - lint
      - py37-core
